apiVersion: v1
kind: Secret
metadata:
  name: metacleaner-secrets
  namespace: metacleaner
  # Copy this file to secrets.local.yaml (ignored by Git) and replace placeholders before applying
type: Opaque
stringData:
  DB_HOST: metacleaner-db
  DB_PORT: "3306"
  DB_USER: REPLACE_DB_USERNAME
  DB_PASSWORD: REPLACE_DB_PASSWORD
  DB_NAME: REPLACE_DB_NAME
  CLEANER_API_KEY: REPLACE_CLEANER_API_KEY
  SECRET_KEY: REPLACE_FLASK_SECRET_KEY
