FROM python:3.12-slim-bookworm

RUN apt-get update && apt-get install -y exiftool curl && rm -rf /var/lib/apt/lists/*

WORKDIR /app
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
COPY cleaner.py .

EXPOSE 5001
ENV FLASK_APP=cleaner.py
ENV FLASK_RUN_HOST=0.0.0.0
ENV FLASK_RUN_PORT=5001

CMD ["flask", "run"]
